
[EMC]
MACHINE = Remora-NucleoHat
DEBUG = 0
VERSION = 1.1

[DISPLAY]
DISPLAY = axis
CYCLE_TIME = 0.100
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
ARCDIVISION = 64
MAX_FEED_OVERRIDE = 1.5
MIN_SPINDLE_OVERRIDE = 0.5
MAX_SPINDLE_OVERRIDE = 1.5
DEFAULT_LINEAR_VELOCITY = 20.00
MIN_LINEAR_VELOCITY = 1
MAX_LINEAR_VELOCITY = 80
DEFAULT_ANGULAR_VELOCITY = 20.00
MIN_ANGULAR_VELOCITY = 1
MAX_ANGULAR_VELOCITY = 90
PROGRAM_PREFIX = ~/linuxcnc/nc_files
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 5
INCREMENTS = 50mm 10mm 5mm 1mm .5mm .1mm .05mm .01mm

[KINS]
JOINTS = 5
KINEMATICS =trivkins coordinates=XYZAB

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[RS274NGC]
PARAMETER_FILE = linuxcnc.var
SUBROUTINE_PATH = ~/linuxcnc/subroutines
USER_M_PATH = ~/linuxcnc/m_codes

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
COMM_WAIT = 0.010
BASE_PERIOD = 0
SERVO_PERIOD = 1000000

[HAL]
HALUI = halui
HALFILE = remora-NucleoHat.hal
POSTGUI_HALFILE = postgui_call_list.hal

[HALUI]
FEED_OVERRIDE = YES
SPINDLE_OVERRIDE = YES

[TRAJ]
COORDINATES =  X Y Z A B
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
CYCLE_TIME = 0.010
DEFAULT_LINEAR_VELOCITY = 50.00
MAX_LINEAR_VELOCITY = 250.00
NO_FORCE_HOMING = 1

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[AXIS_X]
MIN_LIMIT = -10
MAX_LIMIT = 160
MAX_VELOCITY = 80
MAX_ACCELERATION = 250

[JOINT_0]
TYPE = LINEAR
MIN_LIMIT = -10
MAX_LIMIT = 160
MAX_VELOCITY = 80
MAX_ACCELERATION = 250
STEPGEN_MAXACCEL = 500
SCALE = 500
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 300
FF1_GAIN= 0.1
DEADBAND= 0.002
HOME_SEQUENCE = 1
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
HOME_OFFSET = -5
HOME_SEARCH_VEL = -20
HOME_LATCH_VEL = 5
HOME_FINAL_VEL = 2

[AXIS_Y]
MIN_LIMIT = -10
MAX_LIMIT = 110
MAX_VELOCITY = 80
MAX_ACCELERATION = 250

[JOINT_1]
TYPE = LINEAR
MIN_LIMIT = -10
MAX_LIMIT = 110
MAX_VELOCITY = 80
MAX_ACCELERATION = 250
STEPGEN_MAXACCEL = 500
SCALE = 500
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 300
FF1_GAIN= 0.1
DEADBAND= 0.002
HOME_SEQUENCE = 1
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
HOME_OFFSET = -5
HOME_SEARCH_VEL = -20
HOME_LATCH_VEL = 5
HOME_FINAL_VEL = 2

[AXIS_Z]
MIN_LIMIT = -100
MAX_LIMIT = 0
MAX_VELOCITY = 80
MAX_ACCELERATION = 250

[JOINT_2]
TYPE = LINEAR
MIN_LIMIT = -100
MAX_LIMIT = 0
MAX_VELOCITY = 80
MAX_ACCELERATION = 250
STEPGEN_MAXACCEL = 500
SCALE = 500
FERROR = 5
MIN_FERROR = 0.5
P_GAIN= 300
FF1_GAIN= 0.1
DEADBAND= 0.002
HOME_SEQUENCE = 0
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
HOME_OFFSET = 2
HOME_SEARCH_VEL = 20
HOME_LATCH_VEL = -5
HOME_FINAL_VEL = 2

[AXIS_A]
MIN_LIMIT = -45
MAX_LIMIT = 45
MAX_VELOCITY = 90
MAX_ACCELERATION = 250

[JOINT_3]
TYPE = ANGULAR
MIN_LIMIT = -45
MAX_LIMIT = 45
MAX_VELOCITY = 90
MAX_ACCELERATION = 250
STEPGEN_MAXACCEL = 500
# A Axis gear reducer. Spinea TS 070-075-TB-P11-0154 - 75:1 gear ratio. 500 steps per rev x 2 (half step) x 75 gear / 360 = 208.3333
SCALE = 208.3333
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 300
FF1_GAIN= 0.1
DEADBAND= 0.01
HOME_SEQUENCE = 2
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
# Axis limit switches are ~58.5 degrees apart = -29.25 ideal offset. Some dial indicator work helped eliminate further error.
#HOME_OFFSET = -28.867 : added 0.024, to bring it forward a bit
HOME_OFFSET = -28.843
HOME_SEARCH_VEL = -10
HOME_LATCH_VEL = 2
HOME_FINAL_VEL = 15


[AXIS_B]
MIN_LIMIT = -200
MAX_LIMIT = 60
MAX_VELOCITY = 50
MAX_ACCELERATION = 250
WRAPPED_ROTARY = 1

[JOINT_4]
TYPE = ANGULAR
MIN_LIMIT = -200
MAX_LIMIT = 60
MAX_VELOCITY = 50
MAX_ACCELERATION = 250
STEPGEN_MAXACCEL = 500
SCALE = 176.3
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 300
FF1_GAIN= 0.01
DEADBAND= 0.01
# HOME has been set to 1 for all other axis as there are shared home / limit switches to prevent it from being locked at home, but B axis has a home switch at centre of axis
HOME_SEQUENCE = 2
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
# the home sensor is quite wide on this one, had to do some dial indicator work to get it
HOME = 0
HOME_OFFSET = 12.05
HOME_SEARCH_VEL = -25
HOME_LATCH_VEL = 2
HOME_FINAL_VEL = 2
