
[EMC]
MACHINE = Remora-NucleoHat
DEBUG = 0
VERSION = 1.1

[DISPLAY]
DISPLAY = axis
TOOL_EDITOR = tooledit
CYCLE_TIME = 0.100
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
ARCDIVISION = 64
MAX_FEED_OVERRIDE = 1.5
MIN_SPINDLE_OVERRIDE = 0.5
MAX_SPINDLE_OVERRIDE = 1.5
DEFAULT_LINEAR_VELOCITY = 20.00
MIN_LINEAR_VELOCITY = 1
MAX_LINEAR_VELOCITY = 75
DEFAULT_ANGULAR_VELOCITY = 20.00
MIN_ANGULAR_VELOCITY = 1
MAX_ANGULAR_VELOCITY = 360
PROGRAM_PREFIX = ~/linuxcnc/nc_files
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 5
INCREMENTS = 50mm 10mm 5mm 1mm .5mm .1mm .05mm .01mm

[KINS]
JOINTS = 5
KINEMATICS = xyzab_tdr_kins
# NOTE - z-offset has not yet been set, will need to set up fixturing before we can do this. 

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[RS274NGC]
PARAMETER_FILE = linuxcnc.var
SUBROUTINE_PATH = ~/linuxcnc/subroutines
USER_M_PATH = ~/linuxcnc/m_codes

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
COMM_WAIT = 0.010
BASE_PERIOD = 0
SERVO_PERIOD = 1000000

[HAL]
HALUI = halui
HALFILE = remora-NucleoHat.hal
POSTGUI_HALFILE = postgui_call_list.hal

[HALUI]
FEED_OVERRIDE = YES
SPINDLE_OVERRIDE = YES

[TRAJ]
COORDINATES =  X Y Z A B
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
CYCLE_TIME = 0.010
DEFAULT_LINEAR_VELOCITY = 40
MAX_LINEAR_VELOCITY = 75
MAX_ANGULAR_VELOCITY = 360
ACCELERATION = 225
NO_FORCE_HOMING = 1

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

# X Axis
[AXIS_X]
MIN_LIMIT = -10
MAX_LIMIT = 150
MAX_VELOCITY = 60
MAX_ACCELERATION = 350

[JOINT_0]
TYPE = LINEAR
MIN_LIMIT = -10
MAX_LIMIT = 150
MAX_VELOCITY = 60
MAX_ACCELERATION = 350
STEPGEN_MAXACCEL = 500
SCALE = 501
BACKLASH = 0.15
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 60
FF1_GAIN= 0.1
DEADBAND= 0.002
HOME_SEQUENCE = 1
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
HOME_OFFSET = -5
HOME_SEARCH_VEL = -20
HOME_LATCH_VEL = 5
HOME_FINAL_VEL = 2

# Y Axis
[AXIS_Y]
MIN_LIMIT = -10
MAX_LIMIT = 110
MAX_VELOCITY = 20
MAX_ACCELERATION = 120

[JOINT_1]
TYPE = LINEAR
MIN_LIMIT = -10
MAX_LIMIT = 110
MAX_VELOCITY = 20
MAX_ACCELERATION = 120
STEPGEN_MAXACCEL = 150
SCALE = 502
BACKLASH = 0.05
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 60
FF1_GAIN= 0.1
DEADBAND= 0.002
HOME_SEQUENCE = 1
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
HOME_OFFSET = -5
HOME_SEARCH_VEL = -15
HOME_LATCH_VEL = 5
HOME_FINAL_VEL = 2

# Z Axis
[AXIS_Z]
MIN_LIMIT = -90
MAX_LIMIT = 5
MAX_VELOCITY = 60
MAX_ACCELERATION = 350

[JOINT_2]
TYPE = LINEAR
MIN_LIMIT = -90
MAX_LIMIT = 5
MAX_VELOCITY = 60
MAX_ACCELERATION = 350
STEPGEN_MAXACCEL = 500
SCALE = 501
# Seem to be experencing some slippage, potentially need to play with the step generators to see if maybe the step/dir timing might be off??
FERROR = 5
MIN_FERROR = 0.5
P_GAIN= 80
FF1_GAIN = 0.1
DEADBAND = 0.002
HOME_SEQUENCE = 0
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
HOME_OFFSET = 2
HOME_SEARCH_VEL = 20
HOME_LATCH_VEL = -5
HOME_FINAL_VEL = 2

# A AXIS

[AXIS_A]
MIN_LIMIT = -32
MAX_LIMIT = 32
MAX_VELOCITY = 300
MAX_ACCELERATION = 1200

[JOINT_3]
TYPE = ANGULAR
MIN_LIMIT = -32
MAX_LIMIT = 32
MAX_VELOCITY = 200
MAX_ACCELERATION = 400
STEPGEN_MAXACCEL = 800
# A Axis gear reducer. Spinea TS 070-075-TB-P11-0154 - 75:1 gear ratio. 500 steps per rev x 2 (half step) x 75 gear / 360 = 208.3333
SCALE = -104.17
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 80
FF1_GAIN= 0.1
DEADBAND= 0.01
HOME_SEQUENCE = 2
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
# Axis limit switches are ~60 degrees apart = -30 is ideal offset but the interruptor has some odd geometry 
HOME_OFFSET = 28.818
HOME_SEARCH_VEL = 10
HOME_LATCH_VEL = -2
HOME_FINAL_VEL = 15

# B AXIS
[AXIS_B]
MIN_LIMIT = -999
MAX_LIMIT = 999
MAX_VELOCITY = 360
MAX_ACCELERATION = 1500

[JOINT_4]
TYPE = ANGULAR
MIN_LIMIT = -999
MAX_LIMIT = 999
WRAPPED_ROTARY = 1
MAX_VELOCITY = 360
MAX_ACCELERATION = 1500
STEPGEN_MAXACCEL = 1875
# Seems to be a 64:1 gear ratio in the B axis, unit is sealed and no makers mark
SCALE = 88.89
FERROR = 9.0
MIN_FERROR = 0.5
P_GAIN= 80
FF1_GAIN= 0.1
DEADBAND= 0.01
HOME_SEQUENCE = 2
HOME_IGNORE_LIMITS = YES
HOME_USE_INDEX = NO
HOME = 0
#HOME_OFFSET = -2.340 # change of 0.045
HOME_OFFSET = -2.385
HOME_SEARCH_VEL = 25
HOME_LATCH_VEL = -2
HOME_FINAL_VEL = 2
